(function(){'use strict';
var viewport=document.getElementById('viewport'),canvas=document.getElementById('canvas'),eventsLayer=document.getElementById('events'),ticksLayer=document.getElementById('ticks'),data,start,end,px,offset=160;
function yearToX(year){return(year-start)*px+offset}
function escapeHtml(value){return String(value==null?'':value).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]})}
function eraFor(year){return year<907?'唐朝':year<960?'五代十国':year<1271?'宋朝':year<1368?'元朝':year<1644?'明朝':year<1912?'清朝':year<1949?'中华民国':'中华人民共和国'}
function assignLanes(items){var ends=[];return items.slice().sort(function(a,b){return a.year-b.year}).map(function(event){var width=Math.max(190,Math.min(240,event.title.length*17+80)),left=yearToX(event.year),lane=0;while(ends[lane]!==undefined&&left-ends[lane]<28)lane++;ends[lane]=left+width;return{event:event,lane:lane}})}
function renderEvent(item){var event=item.event,el=document.createElement('article');el.className='event '+event.side;el.style.left=yearToX(event.year)+'px';el.style.setProperty('--lane',item.lane);el.innerHTML='<button class="card" type="button"><span class="date">'+escapeHtml(event.year+' · '+event.category)+'</span><strong>'+escapeHtml(event.title)+'</strong><span class="summary">'+escapeHtml(event.description)+'</span></button><span class="stem"></span>';el.querySelector('.card').addEventListener('click',function(){document.querySelectorAll('.event.active').forEach(function(active){active.classList.remove('active')});el.classList.add('active');openDetail(event)});eventsLayer.appendChild(el)}
function openDetail(event){var detail=document.getElementById('detail');document.getElementById('detailType').textContent=event.category+' · '+event.year;document.getElementById('detailTitle').textContent=event.title;document.getElementById('detailText').textContent=event.description;detail.classList.add('show')}
function updateHeader(){var year=Math.round(start+(viewport.scrollLeft+viewport.clientWidth/2-offset)/px);year=Math.max(start,Math.min(end,year));document.getElementById('currentYear').textContent=year;document.getElementById('eraName').textContent=eraFor(year)}
function initTimeline(config){data=config.events||[];start=config.meta.startYear;end=config.meta.endYear;px=config.meta.pixelsPerYear;canvas.style.width=(yearToX(end)+300)+'px';ticksLayer.innerHTML='';eventsLayer.innerHTML='';for(var year=start;year<=end;year+=10){var tick=document.createElement('span');tick.className='tick';tick.textContent=year;tick.style.left=yearToX(year)+'px';ticksLayer.appendChild(tick)}['top','bottom'].forEach(function(side){assignLanes(data.filter(function(event){return event.side===side})).forEach(renderEvent)});viewport.scrollLeft=Math.max(0,yearToX(config.meta.initialYear)-viewport.clientWidth/2);updateHeader()}
document.getElementById('closeDetail').addEventListener('click',function(){document.getElementById('detail').classList.remove('show');document.querySelectorAll('.event.active').forEach(function(event){event.classList.remove('active')})});document.querySelectorAll('.quick button').forEach(function(button){button.addEventListener('click',function(){viewport.scrollTo({left:yearToX(Number(button.dataset.year))-viewport.clientWidth/2,behavior:'smooth'})})});viewport.addEventListener('scroll',updateHeader);viewport.addEventListener('wheel',function(event){if(Math.abs(event.deltaY)>Math.abs(event.deltaX)){event.preventDefault();viewport.scrollLeft+=event.deltaY}},{passive:false});
/* 时间线清单由构建生成（npm run build）；双击 HTML 的 file:// 打开方式不再支持。 */
fetch('timeline-manifest.json').then(function(response){if(!response.ok)throw new Error('HTTP '+response.status);return response.json()}).then(initTimeline).catch(function(error){console.error('时间线清单载入失败：请先运行 npm run build',error)});
})();
