(function(){'use strict';
var viewport=document.getElementById('viewport'),canvas=document.getElementById('canvas'),eventsLayer=document.getElementById('events'),ticksLayer=document.getElementById('ticks'),data,start,end,px,offset=160;
function yearToX(year){return(year-start)*px+offset}
function escapeHtml(value){return String(value==null?'':value).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]})}
function eraFor(year){return year<907?'唐朝':year<960?'五代十国':year<1271?'宋朝':year<1368?'元朝':year<1644?'明朝':year<1912?'清朝':year<1949?'中华民国':'中华人民共和国'}
function assignLanes(items){var ends=[];return items.slice().sort(function(a,b){return a.year-b.year}).map(function(event){var width=Math.max(190,Math.min(240,event.title.length*17+80)),left=yearToX(event.year),lane=0;while(ends[lane]!==undefined&&left-ends[lane]<28)lane++;ends[lane]=left+width;return{event:event,lane:lane}})}
function renderEvent(item){var event=item.event,el=document.createElement('article');el.className='event '+event.side;el.style.left=yearToX(event.year)+'px';el.style.setProperty('--lane',item.lane);el.innerHTML='<button class="card" type="button"><span class="date">'+escapeHtml(event.year+' · '+event.category)+'</span><strong>'+escapeHtml(event.title)+'</strong><span class="summary">'+escapeHtml(event.description)+'</span></button><span class="stem"></span>';el.querySelector('.card').addEventListener('click',function(){document.querySelectorAll('.event.active').forEach(function(active){active.classList.remove('active')});el.classList.add('active');openDetail(event)});eventsLayer.appendChild(el)}
function openDetail(event){var detail=document.getElementById('detail');document.getElementById('detailType').textContent=event.category+' · '+event.year;document.getElementById('detailTitle').textContent=event.title;document.getElementById('detailText').textContent=event.detail||event.description;var gallery=document.getElementById('detailGallery');gallery.innerHTML='';(event.images||[]).forEach(function(image){var figure=document.createElement('figure');figure.innerHTML='<img src="'+escapeHtml(image.src)+'" alt="'+escapeHtml(image.alt||event.title)+'"><figcaption>'+escapeHtml(image.caption||'')+'</figcaption>';gallery.appendChild(figure)});detail.classList.add('show')}
function updateHeader(){var year=Math.round(start+(viewport.scrollLeft+viewport.clientWidth/2-offset)/px);year=Math.max(start,Math.min(end,year));document.getElementById('currentYear').textContent=year;document.getElementById('eraName').textContent=eraFor(year)}
function initTimeline(config){data=config.events||[];start=config.meta.startYear;end=config.meta.endYear;px=config.meta.pixelsPerYear;canvas.style.width=(yearToX(end)+300)+'px';ticksLayer.innerHTML='';eventsLayer.innerHTML='';for(var year=start;year<=end;year+=10){var tick=document.createElement('span');tick.className='tick';tick.textContent=year;tick.style.left=yearToX(year)+'px';ticksLayer.appendChild(tick)}['top','bottom'].forEach(function(side){assignLanes(data.filter(function(event){return event.side===side})).forEach(renderEvent)});viewport.scrollLeft=Math.max(0,yearToX(config.meta.initialYear)-viewport.clientWidth/2);updateHeader()}
document.getElementById('closeDetail').addEventListener('click',function(){document.getElementById('detail').classList.remove('show');document.querySelectorAll('.event.active').forEach(function(event){event.classList.remove('active')})});document.querySelectorAll('.quick button').forEach(function(button){button.addEventListener('click',function(){viewport.scrollTo({left:yearToX(Number(button.dataset.year))-viewport.clientWidth/2,behavior:'smooth'})})});viewport.addEventListener('scroll',updateHeader);viewport.addEventListener('wheel',function(event){if(Math.abs(event.deltaY)>Math.abs(event.deltaX)){event.preventDefault();viewport.scrollLeft+=event.deltaY}},{passive:false});
var fallback={meta:{startYear:618,endYear:2025,pixelsPerYear:8,initialYear:1807},events:[{year:618,title:'唐朝建立',description:'李渊建立唐朝，中国进入开放繁盛的时代。',category:'中国历史',side:'top'},{year:635,title:'景教传入长安',description:'叙利亚基督教传统传入唐代中国，留下大秦景教流行中国碑。',category:'基督教在华',side:'bottom'},{year:907,title:'唐朝灭亡',description:'唐朝结束，中国进入五代十国时期。',category:'中国历史',side:'top'},{year:960,title:'宋朝建立',description:'赵匡胤建立宋朝，海上贸易与城市文化持续发展。',category:'中国历史',side:'top'},{year:1271,title:'元朝建立',description:'元朝建立，欧亚交通加强，基督教传统再次接触中国。',category:'中国历史',side:'top'},{year:1294,title:'天主教士抵达大都',description:'方济各会士在元大都活动，形成早期西方基督教在华记忆。',category:'基督教在华',side:'bottom'},{year:1368,title:'明朝建立',description:'朱元璋建立明朝。',category:'中国历史',side:'top'},{year:1600,title:'利玛窦进入北京',description:'天主教耶稣会士在明末进入中国，开启近代基督教来华的新阶段。',category:'基督教在华',side:'bottom'},{year:1644,title:'明清易代',description:'清军入关，明朝灭亡，清朝建立。',category:'中国历史',side:'top'},{year:1807,title:'马礼逊抵达广州',description:'Robert Morrison 抵达广州，成为第一位来华的新教传教士。',category:'新教历史',side:'bottom',detail:'1807年，英国传教士马礼逊抵达广州，开启了近代新教传入中国大陆的历史。',images:[]},{year:1840,title:'鸦片战争',description:'第一次鸦片战争爆发，中国近代史由此展开。',category:'中国历史',side:'top'},{year:1842,title:'《南京条约》签订',description:'五口通商，西方传教士获得更多进入中国的机会。',category:'中国历史',side:'top'},{year:1853,title:'太平天国运动',description:'洪秀全建立太平天国，基督教思想在中国社会产生复杂影响。',category:'中国历史',side:'top'},{year:1865,title:'戴德生创立内地会',description:'James Hudson Taylor 创立 China Inland Mission，深入中国内地传教。',category:'新教历史',side:'bottom'},{year:1900,title:'义和团运动',description:'义和团运动与庚子事变，对教会与传教士造成巨大冲击。',category:'中国历史',side:'top'},{year:1912,title:'中华民国成立',description:'清帝退位，中华民国成立。',category:'中国历史',side:'top'},{year:1919,title:'五四运动',description:'新文化运动兴起，基督教在中国展开本色化反思。',category:'中国历史',side:'top'},{year:1922,title:'中华基督教会成立',description:'中国教会走向联合与自治，本土教牧力量逐渐成长。',category:'新教历史',side:'bottom'},{year:1949,title:'中华人民共和国成立',description:'中国历史进入新的阶段。',category:'中国历史',side:'top'},{year:1951,title:'差会全面撤离',description:'外国传教士离开中国大陆，中国教会进入新的历史时期。',category:'新教历史',side:'bottom'},{year:1979,title:'教会恢复公开聚会',description:'改革开放后，基督教活动逐步恢复，教堂陆续重开。',category:'新教历史',side:'bottom'},{year:1982,title:'三自爱国运动',description:'中国基督教继续推进自治、自养、自传。',category:'新教历史',side:'bottom'},{year:2025,title:'当代中国教会',description:'中国大陆基督教在城市与乡村持续发展，面临新的处境与挑战。',category:'新教历史',side:'bottom'}]};
/* 直接双击 HTML 时使用这里的数据，避免 file:// 浏览器禁止 fetch JSON。部署到服务器时，可将同样结构维护在 timeline-data.json 中。 */
initTimeline(fallback);
})();
